Homework3
made-mlops-2022/Oleg_Naidovich pull request #3
Opened 2022-12-08 21:50 UTC by oleg-nai

Основная часть:

[x] Поднимите airflow локально, используя docker compose (можно использовать из примера https://github.com/made-ml-in-prod-2021/airflow-examples/)

[x] Реализуйте dag, который генерирует данные для обучения модели (генерируйте данные -- можете использовать как генератор синтетики из первой дз, так и что-то из датасетов sklearn). Вам важно проэмулировать ситуации постоянно поступающих данных (5 баллов)
* записывайте данные в /data/raw/{{ ds }}/data.csv и /data/raw/{{ ds }}/target.csv
[x] Реализуйте dag, который обучает модель еженедельно, используя данные за текущий день. В вашем пайплайне должно быть как минимум 4 стадии, но дайте волю своей фантазии =) (10 баллов)
* подготовить данные для обучения (например, считать из /data/raw/{{ ds }} и положить /data/processed/{{ ds }}/train_data.csv)
* расплитить их на train/val
* обучить модель на train, сохранить в /data/models/{{ ds }}
* провалидировать модель на val (сохранить метрики к модельке)
* Реализуйте dag, который использует модель ежедневно (5 баллов)

принимает на вход данные из пункта 1 (data.csv)
считывает путь до модельки из airflow variables (идея в том, что когда нам нравится другая модель и мы хотим ее на прод)
делает предсказание и записывает их в /data/predictions/{{ ds }}/predictions.csv

[x] поставить все необходимые пакеты в образ с airflow и использовать BashOperator, PythonOperator (1 балл)
 использовать DockerOperator -- тогда выполнение каждой из тасок должно запускаться в собственном контейнере
[x] все даги реализованы только с помощью DockerOperator (пример https://github.com/made-ml-in-prod-2021/airflow-examples/blob/main/dags/11_docker.py). По технике, вы можете использовать такую же структуру как в примере, пакуя в разные докеры скрипты, можете использовать общий докер с вашим пакетом, но с разными точками входа для разных тасок. Прикольно, если вы покажете, что для разных тасок можно использовать разный набор зависимостей (10 баллов)

[x]  Традиционно, самооценка (1 балл)

Total sum: 32

2022-12-25 16:55 UTC, SVizor42 commented on airflow_ml_dags/docker-compose.yml
> +  - AIRFLOW__CORE__LOAD_EXAMPLES=True
Примеры лучше отключить для удобства

2022-12-25 17:02 UTC, SVizor42 commented on airflow_ml_dags/images/airflow-generate-data/Dockerfile
> +COPY generate_data.py synthetic_data.csv requirements.txt /
Зачем копировать файл с зависимостями и не устанавливать их?

2022-12-25 17:08 UTC, SVizor42 requested changes
Комментарии:
1. Нужно добавить метку ДЗ `hw3`.
2. По п.4 - тут возможен только один из вариантов, т.е. баллы не суммируются.
3. Работа отправлена на проверку после софт дедлайна, будет оценена со штрафом.
4. Не нашел скриншотов.

> Чтобы получить баллы, сделайте скриншоты списка всех дагов и каждого графа по отдельности (в исполненном без ошибок виде) и прикрепите их в описание пулл реквеста.

Прошу внести правки.

2022-12-30 13:28 UTC, SVizor42 approved these changes
К сожалению, скриншоты так и не появились. Забираю 2 балла в качестве штрафа.

**Сумма: 31 * 0.6 - 2 = 16.6 балла**

Ветку можно сливать

2022-12-30 15:37 UTC, merged

2022-12-30 15:44 UTC, oleg-nai commented
Спасибо! не забудьте на портале отметить =)